# Generated by Django 3.2.8 on 2021-10-22 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20211022_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 22, 17, 5, 52, 912151)),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
