# Generated by Django 3.2.8 on 2021-10-22 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20211022_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 22, 13, 23, 0, 254964, tzinfo=utc)),
        ),
    ]
