# Generated by Django 3.2.8 on 2021-10-22 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_person_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 22, 13, 25, 32, 645026, tzinfo=utc)),
        ),
    ]
