# Generated by Django 3.2.8 on 2021-10-22 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
