# Generated by Django 3.2.8 on 2021-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='issue_date',
            field=models.DateField(auto_now=True),
        ),
    ]
