# Generated by Django 3.2.8 on 2021-10-23 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_alter_person_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='card_number',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='issue_date',
            field=models.DateField(default=datetime.date(2021, 10, 23)),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=48),
        ),
    ]
